Config = {}

-- Only for animal skins
Config.Controls = {
    Attack = 0x07CE1E61, -- LEFT MOUSE CLICK -- Attacks other players, NPCs, or animals
    Stalk = 0x1A3EABBB, -- F -- Crouches simulating stalking
}

Config.MenuAlign = "top-right" -- change align menu -- top-left -- top-center

Config.Command = {
    Admin = "pedadmin", -- Command for the admin to authorize, deny, or delete a player's ped
    Player = "pedmenu", -- Command for the player to preview, request, and manage their peds
}

Config.Text = {
    Menu = {
        Open = "Open",
        MyPeds = "My Peds",
        AutorPeds = "View your authorized peds",
        Menupeds = "Peds Menu",
        Sellect = "Select an option",
        Request = "Request",
        Select = "Select a ped",
        Authorized = "Authorized Peds",
        RequestAdmin = "Request from admin",
        SendRequest = "Send request to an admin",
        RequestPed = "Request Ped",
        Options = "Options",
        Player = "Player:",
        SeeAuthorized = "View authorized peds",
        Applications = "Ped Requests",
        AdminOptions = "Admin Options",
        Approve = "Authorize",
        Reject = "Reject",
        Grant = "Grant Ped",
        SelectPlayer = "Select a player",
        Delete = "Select ped to delete",
        YourPeds = "Your authorized ped",
    },
    Notify = {
        Title = "Ped Menu",
        SentAdmin = "Request sent to the admin.",
        NotPermission = "You don't have permission.",
        AuthorizedCorrected = "Ped successfully authorized.",
        AuthorizedError = "Error: request not found.",
        DeleteCorrected = "Request successfully deleted.",
        DeleteError = "Error deleting the request.",
        DeletePedCorrected = "Ped successfully deleted.",
        DeletePedError = "Error deleting the ped.",
    },
}

Config.PedList = {
    ["MAN PEDS"] = {
        "A_M_M_ARMTOWNFOLK_01",
        "A_M_M_ARMTOWNFOLK_02",
        "A_M_M_ASBMINER_01",
        "A_M_M_ASBMINER_02",
        "A_M_M_ASBMINER_03",
        "A_M_M_ASBMINER_04",
        "A_M_M_ASBTOWNFOLK_01",
        "A_M_M_ASBTOWNFOLK_01_LABORER",
        "A_M_M_BLWOBESEMEN_01",
        "A_M_M_BTCOBESEMEN_01",
        "A_M_M_GUATOWNFOLK_01",
        "A_M_M_LAGTOWNFOLK_01",
        "A_M_M_LOWERSDTOWNFOLK_01",
        "A_M_M_LOWERSDTOWNFOLK_02",
        "A_M_M_MIDDLESDTOWNFOLK_01",
        "A_M_M_MIDDLESDTOWNFOLK_02",
        "A_M_M_MIDDLESDTOWNFOLK_03",
        "A_M_M_NBXDOCKWORKERS_01",
        "A_M_M_NBXUPPERCLASS_01",
        "A_M_M_RANCHER_01",
        "A_M_M_RHDDEPUTYRESIDENT_01",
        "A_M_M_RHDOBESEMEN_01",
        "A_M_M_RHDTOWNFOLK_01",
        "A_M_M_RHDTOWNFOLK_01_LABORER",
        "A_M_M_RHDTOWNFOLK_02",
        "A_M_M_RHDUPPERCLASS_01",
        "A_M_M_SDCHINATOWN_01",
        "A_M_M_SDDOCKWORKERS_02",
        "A_M_M_SKPPRISONER_01",
        "A_M_M_SKPPRISONLINE_01",
        "A_M_M_STRDEPUTYRESIDENT_01",
        "A_M_M_STRTOWNFOLK_01",
        "A_M_M_TUMTOWNFOLK_01",
        "A_M_M_TUMTOWNFOLK_02",
        "A_M_M_UPPERTRAINPASSENGERS_01",
        "A_M_M_VALTOWNFOLK_01",
        "A_M_M_VALTOWNFOLK_02",
        "A_M_M_VHTTOWNFOLK_01",
        "A_M_M_WAPWARRIORS_01",
        "A_M_O_GUATOWNFOLK_01",
        "A_M_O_LAGTOWNFOLK_01",
        "A_M_O_SDCHINATOWN_01",
        "A_M_O_SDUPPERCLASS_01",
        "A_M_O_WAPTOWNFOLK_01",
        "A_M_Y_ASBMINER_01",
        "A_M_Y_ASBMINER_02",
        "A_M_Y_ASBMINER_03",
        "A_M_Y_ASBMINER_04",
        "U_M_M_ARMGENERALSTOREOWNER_01",
        "U_M_M_ARMTRAINSTATIONWORKER_01",
        "U_M_M_BIVFOREMAN_01",
        "U_M_M_BHT_BANDITOMINE",
        "U_M_M_BHT_BANDITOSHACK",
        "U_M_M_BHT_BLACKWATERHUNT",
        "U_M_M_BHT_ODRISCOLLDRUNK",
        "U_M_M_BHT_ODRISCOLLMAULED",
        "U_M_M_BHT_SKINNERSEARCH",
        "U_M_M_CRDHOMESTEADTENANT_01",
        "U_M_M_CRDHOMESTEADTENANT_02",
        "U_M_M_CREOLECAPTAIN_01",
        "U_M_M_CZPHOMESTEADFATHER_01",
        "U_M_M_DORHOMESTEADHUSBAND_01",
        "U_M_M_EMRFARMHAND_03",
        "U_M_M_FINALE2_AA_UPPERCLASS_01",
        "U_M_M_GALASTRINGQUARTET_01",
        "U_M_M_GALASTRINGQUARTET_02",
        "U_M_M_GALASTRINGQUARTET_03",
        "U_M_M_GALASTRINGQUARTET_04",
        "U_M_M_HHRRANCHER_01",
        "U_M_M_HTLRANCHERBOUNTY_01",
        "U_M_M_LNSWORKER_01",
        "U_M_M_LNSWORKER_02",
        "U_M_M_LNSWORKER_03",
        "U_M_M_LNSWORKER_04",
        "U_M_M_LRSHOMESTEADTENANT_01",
        "U_M_M_MFRRANCHER_01",
        "U_M_M_NBXBARTENDER_01",
        "U_M_M_NBXBARTENDER_02",
        "U_M_M_NBXGENERALSTOREOWNER_01",
        "U_M_M_NBXLIVERYWORKER_01",
        "U_M_M_NBXPRIEST_01",
        "U_M_M_RHDBACKUPDEPUTY_01",
        "U_M_M_RHDBACKUPDEPUTY_02",
        "U_M_M_RHDBARTENDER_01",
        "U_M_M_RHDDOCTOR_01",
        "U_M_M_RHDFIDDLEPLAYER_01",
        "U_M_M_RHDSHERIFF_01",
        "U_M_M_RHDTRAINSTATIONWORKER_01",
        "U_M_M_RKFRANCHER_01",
        "U_M_M_RWFRANCHER_01",
        "U_M_M_SDBANKGUARD_01",
        "U_M_M_SDEXOTICSSHOPKEEPER_01",
        "U_M_M_SDPHOTOGRAPHER_01",
        "U_M_M_SDPOLICECHIEF_01",
        "U_M_M_STORY_PIGFARM_01",
        "U_M_M_TUMBARTENDER_01",
        "U_M_M_TUMBUTCHER_01",
        "U_M_M_TUMTRAINSTATIONWORKER_01",
        "U_M_M_UNIBOUNTYHUNTER_02",
        "U_M_M_UNIBOUNTYHUNTER_01",
        "U_M_M_VALBARBER_01",
        "U_M_M_VALBARTENDER_01",
        "U_M_M_VALBUTCHER_01",
        "U_M_M_VALDOCTOR_01",
        "U_M_M_VALSHERIFF_01",
        "U_M_M_VALTOWNFOLK_01",
        "U_M_M_VALTOWNFOLK_02",
        "U_M_M_WALGENERALSTOREOWNER_01",
        "U_M_M_WTCCOWBOY_04",
        "U_M_O_ARMBARTENDER_01",
        "U_M_O_ASBSHERIFF_01",
        "U_M_O_BLWBARTENDER_01",
        "U_M_O_BLWPHOTOGRAPHER_01",
        "U_M_O_BLWPOLICECHIEF_01",
        "U_M_O_CAJHOMESTEAD_01",
        "U_M_O_CMRCIVILWARCOMMANDO_01",
        "U_M_O_MAPWISEOLDMAN_01",
        "U_M_O_PSHRANCHER_01",
        "U_M_O_RIGTRAINSTATIONWORKER_01",
        "U_M_O_VALBARTENDER_01",
        "U_M_O_VHTEXOTICSHOPKEEPER_01",
        "U_M_Y_CAJHOMESTEAD_01",
        "U_M_Y_CZPHOMESTEADSON_01",
        "U_M_Y_CZPHOMESTEADSON_02",
        "U_M_Y_CZPHOMESTEADSON_03",
        "U_M_Y_CZPHOMESTEADSON_04",
        "U_M_Y_CZPHOMESTEADSON_05",
        "U_M_Y_HTLWORKER_01",
        "U_M_Y_HTLWORKER_02",
        "G_M_M_BOUNTYHUNTERS_01",
        "G_M_M_UNIMOUNTAINMEN_01",
        "G_M_M_UNIRANCHERS_01",
        "RE_SAVAGEWAGON_MALES_01",
        "RE_STALKINGHUNTER_MALES_01",
        "RE_LONEPRISONER_MALES_01",
        "RE_PLAYERCAMPSTRANGERS_MALES_01",
        "RE_POLICECHASE_MALES_01",
        "RE_PRISONWAGON_MALES_01",
        "RE_RALLYDISPUTE_MALES_01",
        "RE_RALLYSETUP_MALES_01",
        "RE_RALLY_MALES_01",
        "MSP_INDUSTRY3_MALES_01",
        "MSP_TRAINROBBERY2_MALES_01",
        "RCSP_CALLOWAY_MALES_01",
        "RCSP_FORMYART_MALES_01",
        "MP_ASN_BRAITHWAITEMANOR_MALES_03",
        "S_M_M_AMBIENTBLWPOLICE_01",
        "S_M_M_AMBIENTLAWRURAL_01",
        "S_M_M_AMBIENTSDPOLICE_01",
        "S_M_M_ARMY_01",
        "S_M_M_BARBER_01",
        "S_M_M_BWMWORKER_01",
        "S_M_M_CGHWORKER_01",
        "S_M_M_CKTWORKER_01",
        "S_M_M_DISPATCHLAWRURAL_01",
        "S_M_M_DISPATCHLEADERPOLICE_01",
        "S_M_M_DISPATCHPOLICE_01",
        "S_M_M_LIVERYWORKER_01",
        "S_M_M_MAPWORKER_01",
        "S_M_M_MARKETVENDOR_01",
        "S_M_M_RACRAILWORKER_01",
        "S_M_M_SKPGUARD_01",
        "S_M_M_STGSAILOR_01",
        "S_M_M_TAILOR_01",
        "S_M_M_TRAINSTATIONWORKER_01",
        "S_M_M_TUMDEPUTIES_01",
        "S_M_M_UNIBUTCHERS_01",
        "S_M_M_VALDEPUTY_01",
        "S_M_O_CKTWORKER_01",
        "S_M_Y_ARMY_01",
        "S_M_Y_NEWSPAPERBOY_01",
        "S_M_Y_RACRAILWORKER_01",
    },
    ["WOMEN PEDS"] = {
        "CS_MP_JESSICA",
        "A_F_M_ARMTOWNFOLK_01",
        "A_F_M_ARMTOWNFOLK_02",
        "A_F_M_ASBTOWNFOLK_01",
        "A_F_M_GUATOWNFOLK_01",
        "A_F_M_LAGTOWNFOLK_01",
        "A_F_M_LOWERSDTOWNFOLK_01",
        "A_F_M_LOWERSDTOWNFOLK_02",
        "A_F_M_LOWERSDTOWNFOLK_03",
        "A_F_M_MIDDLESDTOWNFOLK_01",
        "A_F_M_MIDDLESDTOWNFOLK_02",
        "A_F_M_MIDDLESDTOWNFOLK_03",
        "A_F_M_NBXUPPERCLASS_01",
        "A_F_M_RHDTOWNFOLK_01",
        "A_F_M_RHDUPPERCLASS_01",
        "A_F_M_SDCHINATOWN_01",
        "A_F_M_SKPPRISONONLINE_01",
        "A_F_M_STRTOWNFOLK_01",
        "A_F_M_TUMTOWNFOLK_01",
        "A_F_M_TUMTOWNFOLK_02",
        "A_F_M_UPPERTRAINPASSENGERS_01",
        "A_F_M_VALTOWNFOLK_01",
        "A_F_M_VHTTOWNFOLK_01",
        "A_F_M_WAPTOWNFOLK_01",
        "A_F_O_GUATOWNFOLK_01",
        "A_F_O_LAGTOWNFOLK_01",
        "A_F_O_SDCHINATOWN_01",
        "A_F_O_SDUPPERCLASS_01",
        "A_F_O_WAPTOWNFOLK_01",
        "U_F_M_EMRDAUGHTER_01",
        "U_F_M_TLJBARTENDER_01",
        "U_F_M_TUMGENERALSTOREOWNER_01",
        "U_F_M_VALTOWNFOLK_01",
        "U_F_M_VALTOWNFOLK_02",
        "U_F_M_VHTBARTENDER_01",
        "U_F_O_HERMIT_WOMAN_01",
        "U_F_O_WTCTOWNFOLK_01",
        "MP_ASN_SDWEDDING_FEMALES_01",
        "MSP_BOUNTYHUNTER1_FEMALES_01",
        "RE_DEADJOHN_FEMALES_01",
        "RE_TOWNWIDOW_FEMALES_01",
        "S_F_M_BWMWORKER_01",
        "S_F_M_CGHWORKER_01",
        "S_F_M_MAPWORKER_01",
        "CS_ABIGAILROBERTS",
        "CS_ACROBAT",
    },
    ["SPECIAL PEDS"] = {
        "CS_ASBDEPUTY_01",
        "CS_BAPTISTE",
        "CS_BLWPHOTOGRAPHER",
        "CS_BROTHERDORKINS",
        "CS_CAPTAINMONROE",
        "CS_CHAINPRISONER_01",
        "CS_CHAINPRISONER_02",
        "CS_COLFAVOURS",
        "CS_COLMODRISCOLL",
        "CS_CORNWALLTRAINCONDUCTOR",
        "CS_CRACKPOTROBOT",
        "CS_CREOLEDOCTOR",
        "CS_DUNCANGEDDES",
        "CS_DUTCH",
        "CS_EAGLEFLIES",
        "CS_GERMANDAUGHTER",
        "CS_GERMANSON",
        "CS_HESTONJAMESON",
        "CS_JACKMARSTON",
        "CS_JACKMARSTON_TEEN",
        "CS_JAMIE",
        "CS_JOHNWEATHERS",
        "CS_LONDONDERRYSON",
        "CS_MAGNIFICO",
        "CS_MARSHALL_THURWELL",
        "CS_MEDITATINGMONK",
        "CS_MICAHBELL",
        "CS_MILTONANDREWS",
        "CS_MP_BOUNTYHUNTER",
        "CS_MP_MARSHALL_DAVIES",
        "CS_MP_TEDDYBROWN",
        "CS_NBXPOLICECHIEFFORMAL",
        "CS_PRIEST_WEDDING",
        "CS_RAINSFALL",
        "CS_RHODEPUTY_01",
        "CS_RHODEPUTY_02",
        "CS_RINGMASTER",
        "CS_SDDOCTOR_01",
        "CS_SHERIFFOWENS",
        "CS_SISTERCALDERON",
        "CS_STRDEPUTY_01",
        "CS_STRDEPUTY_02",
        "CS_STRSHERIFF_01",
        "CS_SWAMPFREAK",
        "CS_VALDEPUTY_01",
        "CS_VALSHERIFF",
        "CS_VAMPIRE",
        "CS_WAPITIBOY",
        "CS_WATSON_02",
        "CS_TILLY",
        "MP_PREDATOR",
        "MBH_RHODESRANCHER_TEENS_01",
    },
    ["KID PEDS"] = {
        "a_m_y_nbxstreetkids_01",
        "a_m_y_nbxstreetkids_slums_01",
        "a_m_y_sdstreetkids_slums_02",
        "cs_mixedracekid",
        "cs_sd_streetkid_01",
        "cs_sd_streetkid_01a",
        "cs_sd_streetkid_01b",
        "cs_sd_streetkid_02",
        "cs_sdstreetkidthief",
    },
    ["ANIMAL PEDS"] = {
        "A_C_DogHusky_01",
        "a_c_dogaustraliansheperd_01",
        "A_C_DogAmericanFoxhound_01",
        "A_C_DogBluetickCoonhound_01",
        "A_C_DogCatahoulaCur_01",
        "A_C_DogChesBayRetriever_01",
        "A_C_DogCollie_01",
        "A_C_DogHobo_01",
        "A_C_DogHound_01",
        "A_C_DogLab_01",
        "A_C_DogLion_01",
        "A_C_DogPoodle_01",
        "A_C_DogRufus_01",
        "A_C_DogStreet_01",
        "A_C_Wolf_Medium",
        "A_C_Wolf_Small",
        "A_C_Wolf",
        "MP_A_C_WOLF_01",
        "A_C_Bear_01",
        "A_C_BearBlack_01",
        "A_C_Horse_AmericanPaint_Greyovero",
        "A_C_Horse_AmericanPaint_Overo",
        "A_C_Horse_AmericanPaint_SplashedWhite",
        "A_C_Horse_AmericanPaint_Tobiano",
        "A_C_Horse_AmericanStandardbred_Black",
        "A_C_Horse_AmericanStandardbred_Buckskin",
        "A_C_Horse_AmericanStandardbred_Lightbuckskin",
        "A_C_Horse_AmericanStandardbred_PalominoDapple",
        "A_C_Horse_AmericanStandardbred_SilverTailBuckskin",
        "A_C_Horse_Andalusian_DarkBay",
        "A_C_Horse_Andalusian_Perlino",
        "A_C_Horse_Andalusian_RoseGray",
        "A_C_Horse_Appaloosa_BlackSnowflake",
        "A_C_Horse_Appaloosa_Blanket",
        "A_C_Horse_Appaloosa_BrownLeopard",
        "A_C_Horse_Appaloosa_FewSpotted_PC",
        "A_C_Horse_Appaloosa_Leopard",
        "A_C_Horse_Appaloosa_LeopardBlanket",
        "A_C_Horse_Arabian_Black",
        "A_C_Horse_Arabian_Grey",
        "A_C_Horse_Arabian_RedChestnut",
        "A_C_Horse_Arabian_RedChestnut_PC",
        "A_C_Horse_Arabian_RoseGreyBay",
        "A_C_Horse_Arabian_WarpedBrindle_PC",
        "A_C_Horse_Arabian_White",
        "A_C_Horse_Ardennes_BayRoan",
        "A_C_Horse_Ardennes_IronGreyRoan",
        "A_C_Horse_Ardennes_StrawberryRoan",
        "A_C_Horse_Belgian_BlondChestnut",
        "A_C_Horse_Belgian_MealyChestnut",
        "A_C_Horse_Breton_GrulloDun",
        "A_C_Horse_Breton_MealyDappleBay",
        "A_C_Horse_Breton_RedRoan",
        "A_C_Horse_Breton_Sealbrown",
        "A_C_Horse_Breton_Sorrel",
        "A_C_Horse_Breton_SteelGrey",
        "A_C_Horse_Buell_WarVets",
        "A_C_Horse_Criollo_Baybrindle",
        "A_C_Horse_Criollo_Bayframeovero",
        "A_C_Horse_Criollo_Blueroanovero",
        "A_C_Horse_Criollo_Dun",
        "A_C_Horse_Criollo_Marblesabino",
        "A_C_Horse_Criollo_Sorrelovero",
        "A_C_Horse_DutchWarmblood_ChocolateRoan",
        "A_C_Horse_DutchWarmblood_SealBrown",
        "A_C_Horse_DutchWarmblood_SootyBuckskin",
        "A_C_Horse_EagleFlies",
        "A_C_Horse_Gang_arthur",
        "A_C_Horse_Gang_Bill",
        "A_C_Horse_Gang_Charles",
        "A_C_Horse_Gang_Charles_EndlessSummer",
        "A_C_Horse_Gang_Hosea",
        "A_C_Horse_Gang_Javier",
        "A_C_Horse_Gang_John",
        "A_C_Horse_Gang_Karen",
        "A_C_Horse_Gang_Kieran",
        "A_C_Horse_Gang_Lenny",
        "A_C_Horse_Gang_Micah",
        "A_C_Horse_Gang_Sadie",
        "A_C_Horse_Gang_Sadie_EndlessSummer",
        "A_C_Horse_Gang_Sean",
        "A_C_Horse_Gang_Trelawney",
        "A_C_Horse_Gang_Uncle",
        "A_C_Horse_Gang_Uncle_EndlessSummer",
        "A_C_Horse_GypsyCob_PalominoBlagdon",
        "A_C_Horse_GypsyCob_Piebald",
        "A_C_Horse_GypsyCob_Skewbald",
        "A_C_Horse_GypsyCob_SplashedBay",
        "A_C_Horse_GypsyCob_SplashedPiebald",
        "A_C_Horse_GypsyCob_WhiteBlagdon",
        "A_C_Horse_HungarianHalfbred_DarkDappleGrey",
        "A_C_Horse_HungarianHalfbred_FlaxenChestnut",
        "A_C_Horse_HungarianHalfbred_LiverChestnut",
        "A_C_Horse_HungarianHalfbred_PiebaldTobiano",
        "A_C_Horse_John_EndlessSummer",
        "A_C_Horse_KentuckySaddle_Black",
        "A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC",
        "A_C_Horse_KentuckySaddle_ChestnutPinto",
        "A_C_Horse_KentuckySaddle_Grey",
        "A_C_Horse_KentuckySaddle_SilverBay",
        "A_C_Horse_Kladruber_Black",
        "A_C_Horse_Kladruber_Cremello",
        "A_C_Horse_Kladruber_Dapplerosegrey",
        "A_C_Horse_Kladruber_Grey",
        "A_C_Horse_Kladruber_Silver",
        "A_C_Horse_Kladruber_White",
        "A_C_Horse_MissouriFoxTrotter_AmberChampagne",
        "A_C_Horse_MissouriFoxTrotter_Blacktovero",
        "A_C_Horse_MissouriFoxTrotter_BlueRoan",
        "A_C_Horse_MissouriFoxTrotter_Buckskinbrindle",
        "A_C_Horse_MissouriFoxTrotter_DappleGrey",
        "A_C_Horse_MissouriFoxTrotter_SableChampagne",
        "A_C_Horse_MissouriFoxTrotter_SilverDapplePinto",
        "A_C_Horse_Morgan_Bay",
        "A_C_Horse_Morgan_BayRoan",
        "A_C_Horse_Morgan_FlaxenChestnut",
        "A_C_Horse_Morgan_LiverChestnut_PC",
        "A_C_Horse_Morgan_Palomino",
        "A_C_Horse_MP_Mangy_Backup",
        "A_C_Horse_MurfreeBrood_Mange_01",
        "A_C_Horse_MurfreeBrood_Mange_02",
        "A_C_Horse_MurfreeBrood_Mange_03",
        "A_C_Horse_Mustang_BlackOvero",
        "A_C_Horse_Mustang_Buckskin",
        "A_C_Horse_Mustang_ChestnutTovero",
        "A_C_Horse_Mustang_GoldenDun",
        "A_C_Horse_Mustang_GrulloDun",
        "A_C_Horse_Mustang_RedDunOvero",
        "A_C_Horse_Mustang_TigerStripedBay",
        "A_C_Horse_Mustang_WildBay",
        "A_C_Horse_Nokota_BlueRoan",
        "A_C_Horse_Nokota_ReverseDappleRoan",
        "A_C_Horse_Nokota_WhiteRoan",
        "A_C_Horse_NorfolkRoadster_Black",
        "A_C_Horse_NorfolkRoadster_DappledBuckskin",
        "A_C_Horse_NorfolkRoadster_PiebaldRoan",
        "A_C_Horse_NorfolkRoadster_RoseGrey",
        "A_C_Horse_NorfolkRoadster_SpeckledGrey",
        "A_C_Horse_NorfolkRoadster_SpottedTricolor",
        "A_C_Horse_Shire_DarkBay",
        "A_C_Horse_Shire_LightGrey",
        "A_C_Horse_Shire_RavenBlack",
        "A_C_Horse_SuffolkPunch_RedChestnut",
        "A_C_Horse_SuffolkPunch_Sorrel",
        "A_C_Horse_TennesseeWalker_BlackRabicano",
        "A_C_Horse_TennesseeWalker_Chestnut",
        "A_C_Horse_TennesseeWalker_DappleBay",
        "A_C_Horse_TennesseeWalker_FlaxenRoan",
        "A_C_Horse_TennesseeWalker_GoldPalomino_PC",
        "A_C_Horse_TennesseeWalker_MahoganyBay",
        "A_C_Horse_TennesseeWalker_RedRoan",
        "A_C_Horse_Thoroughbred_BlackChestnut",
        "A_C_Horse_Thoroughbred_BloodBay",
        "A_C_Horse_Thoroughbred_Brindle",
        "A_C_Horse_Thoroughbred_DappleGrey",
        "A_C_Horse_Thoroughbred_ReverseDappleBlack",
        "A_C_Horse_Turkoman_Black",
        "A_C_Horse_Turkoman_Chestnut",
        "A_C_Horse_Turkoman_DarkBay",
        "A_C_Horse_Turkoman_Gold",
        "A_C_Horse_Turkoman_Grey",
        "A_C_Horse_Turkoman_Perlino",
        "A_C_Horse_Turkoman_Silver",
        "A_C_Horse_Winter02_01",
        "A_C_HorseMule_01",
        "A_C_HorseMulePainted_01",
        "A_C_Coyote_01",
        "MP_A_C_Coyote_01",
        "A_C_Cougar_01",
        "MP_A_C_Cougar_01",
        "A_C_Panther_01",
        "MP_A_C_Panther_01",
        "A_C_LionMangy_01",
        "a_c_cat_01",
        "A_C_Deer_01",
        "A_C_Buck_01",
        "A_C_Elk_01",
        "A_C_Fox_01",
        "A_C_Goat_01",
        "A_C_Moose_01",
        "A_C_Pig_01",
        "A_C_Sheep_01",
        "A_C_Skunk_01",
        "A_C_Boar_01",
        "A_C_Buffalo_01",
        "a_c_bull_01",
        "A_C_Cow",
        "A_C_BigHornRam_01",
        "a_c_raccoon_01",
        "a_c_rabbit_01",
        "a_c_squirrel_01",
        "a_c_badger_01",
        "A_C_Eagle_01",
        "a_c_sparrow_01",
        "a_c_owl_01",
    },
}

Config.AttackTypes  = {
    {
        models = {
            `A_C_SharkTiger`,
            `A_C_SharkHammerhead_01`
        },
        animation = {
            dict = "creatures_reptile@alligator@melee@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 2.0,
        damage = 75
    },
    {
        models = {
            `A_C_Alligator_01`,
            `MP_A_C_Alligator_01`
        },
        animation = {
            dict = "creatures_reptile@alligator@melee@streamed_core",
            name = "attack"
        },
        radius = 2.5,
        force = 2.0,
        damage = 25
    },
    {
        models = {
            `A_C_Alligator_02`
        },
        animation = {
            dict = "amb_creatures_reptile@gator_giant@nip_attack",
            name = "nip"
        },
        radius = 3.0,
        force = 2.0,
        damage = 25
    },
    {
        models = {
            `A_C_Badger_01`
        },
        animation = {
            dict = "creatures_mammal@badger@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Bear_01`,
            `A_C_BearBlack_01`,
            `MP_A_C_Bear_01`
        },
        animation = {
            dict = "creatures_mammal@bear@melee@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 5.0,
        damage = 30
    },
    {
        models = {
            `A_C_Beaver_01`,
            `MP_A_C_Beaver_01`
        },
        animation = {
            dict = "creatures_mammal@beaver@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Cougar_01`,
            `A_C_Panther_01`,
            `MP_A_C_Cougar_01`,
            `MP_A_C_Panther_01`
        },
        animation = {
            dict = "creatures_mammal@cougar@melee@streamed_core",
            name = "attack"
        },
        radius = 2.0,
        force = 3.0,
        damage = 20
    },
    {
        models = {
            `A_C_Coyote_01`,
            `MP_A_C_Coyote_01`
        },
        animation = {
            dict = "creatures_mammal@coyote@melee@streamed_core",
            name = "attack"
        },
        radius = 2.5,
        force = 2.0,
        damage = 25
    },
    {
        models = {
            `A_C_DogAmericanFoxhound_01`,
            `a_c_dogaustraliansheperd_01`,
            `A_C_DogBluetickCoonhound_01`,
            `A_C_DogCatahoulaCur_01`,
            `A_C_DogChesBayRetriever_01`,
            `A_C_DogCollie_01`,
            `A_C_DogHobo_01`,
            `A_C_DogHound_01`,
            `A_C_DogHusky_01`,
            `A_C_DogLab_01`,
            `A_C_DogLion_01`,
            `A_C_DogPoodle_01`,
            `A_C_DogRufus_01`,
            `A_C_DogStreet_01`,
            `MP_A_C_DogAmericanFoxhound_01`
        },
        animation = {
            dict = "creatures_mammal@dog_pers@melee@streamed_core",
            name = "attack"
        },
        radius = 2.5,
        force = 2.0,
        damage = 20
    },
    {
        models = {
            `A_C_Muskrat_01`
        },
        animation = {
            dict = "creatures_mammal@muskrat@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Raccoon_01`
        },
        animation = {
            dict = "creatures_mammal@raccoon@melee",
            name = "nip_attack"
        },
        radius = 2.0,
        force = 1.0,
        damage = 15
    },
    {
        models = {
            `A_C_Wolf`,
            `MP_A_C_Wolf_01`,
            `A_C_LionMangy_01`
        },
        animation = {
            dict = "creatures_mammal@wolf@melee@attacks@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 3.0,
        damage = 30
    },
    {
        models = {
            `A_C_Wolf_Medium`
        },
        animation = {
            dict = "creatures_mammal@wolf_medium@melee@attacks@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 3.0,
        damage = 25
    },
    {
        models = {
            `A_C_Wolf_Small`
        },
        animation = {
            dict = "creatures_mammal@wolf_small@melee@attacks@streamed_core",
            name = "attack"
        },
        radius = 3.0,
        force = 3.0,
        damage = 20
    }
}

Config.AttackCooldown = 2000
